- name: Create root dir
  become: yes
  file:
    path: "{{ app_root }}"
    state: directory

- name: Create pvenv dir
  become: yes
  file:
    path: "{{ app_root }}/pvenv"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Create data dir
  become: yes
  file:
    path: "{{ app_root }}/data"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  
- name: Files
  become: yes
  synchronize:
    src: "{{ local_root }}/{{ item }}/"
    dest: "{{ app_root }}/{{ item }}"
    archive: no
    recursive: yes
    checksum: yes
    delete: yes
  loop:
    - recipes
    - tempt
    - static
    - templates

- name: Copy individual files
  become: yes
  ansible.builtin.copy:
    src: "{{ local_root }}/{{ item }}"
    dest: "{{ app_root }}/{{ item }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
  loop:
    - requirements.txt
    - manage.py


- name: copy run_gunicorn
  become: yes
  template:
    src: run_gunicorn.j2
    dest: "{{ app_root }}/run_gunicorn"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755

- name: copy envsh
  become: yes
  template:
    src: env.sh.j2
    dest: "{{ app_root }}/env.sh"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0644

