
- include: user.yml
- include: files.yml
- include: logging.yml

- name: install packages
  become: yes
  apt:
    pkg:
      - virtualenv

- name: pip
  become: yes
  pip:
    chdir: "{{ app_root }}"
    virtualenv: pvenv
    virtualenv_python: python3
    requirements: "requirements.txt"

- name: post deploy
  become: yes
  become_user: "{{ app_user }}"
  script: post_deploy.sh
  args:
    chdir: "{{ app_root }}"

- name: post deploy as root
  become: yes
  script: post_deploy_root.sh
  args:
    chdir: "{{ app_root }}"
     
- include: cert.yml  
- include: nginx.yml
  vars:
    site: "{{ subdomain }}"
    site_template: "nginx-site.j2"
- include: systemd.yml
