
- include: user.yml
- include: files.yml
- include: logging.yml

- name: pip
  become: yes
  pip:
    chdir: "{{ app_root }}"
    virtualenv: pvenv
    virtualenv_python: python3
    requirements: "requirements.txt"

- name: post deploy
  become: yes
  become_user: "{{ app_user }}"
  script: post_deploy.sh
  args:
    chdir: "{{ app_root }}"

    
- include: nginx.yml    
- include: systemd.yml
