
- include: user.yml
- include: files.yml
- include: logging.yml
- include: packages.yml

- name: pip
  become: yes
  pip:
    chdir: "{{ ssp_root }}/django"
    virtualenv: ../pvenv
    virtualenv_python: python3
    requirements: "requirements.txt"
    extra_args: -c requirements_frozen.txt

- name: post deploy
  become: yes
  become_user: "{{ ssp_user }}"
  script: post_deploy.sh
  args:
    chdir: "{{ ssp_root }}"

    
- include: nginx.yml    
- include: systemd.yml
