- name: Install nginx
  become: yes
  apt:
    pkg:
    - nginx

- name: "site available {{ site }}"
  become: yes
  register: nginx_avail
  template:
    src: "{{ site_template }}"
    dest: "/etc/nginx/sites-available/{{ site }}"

- name: "site enabled {{ site }}"
  become: yes
  register: nginx_enabled
  file:
    src: "/etc/nginx/sites-available/{{ site }}"
    dest: "/etc/nginx/sites-enabled/{{ site }}"
    state: link

- name: reload nginx
  become: yes
  command: nginx -s reload
  when: nginx_avail.changed or nginx_enabled.changed

- name: Ensure nginx running
  systemd:
    state: started
    enabled: true
    name: nginx    
