- name: Create Group
  become: yes
  group:
    name: "{{ app_group }}"
    state: present

- name: Create User
  become: yes
  user:
    name: "{{ app_user }}"
    create_home: no
    group: "{{ app_group }}"
    shell: "/bin/false"
    
