# Generated by Django 3.2 on 2021-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210502_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='in_planning',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping',
            field=models.BooleanField(default='False'),
        ),
    ]
