# Generated by Django 3.2 on 2021-05-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210506_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='typical_serving_size',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='typical_serving_unit',
            field=models.CharField(default=-1, max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight_per_serving',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=20),
        ),
    ]
