# Generated by Django 3.2 on 2021-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210506_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='typical_serving_size',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='typical_serving_unit',
            field=models.CharField(default='undefined', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight_per_serving',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
