# Generated by Django 3.2 on 2021-05-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210510_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingquant',
            name='unit',
            field=models.CharField(choices=[('GRAM', 'gram'), ('WTOZ', 'wt oz'), ('FLOZ', 'fl oz'), ('CUP', 'cup'), ('TSP', 'tsp'), ('TBSP', 'tbsp'), ('ML', 'ml'), ('CAN', 'can'), ('PINT', 'pint'), ('QUART', 'quart'), ('GALLON', 'gallon'), ('LITER', 'liter'), ('KILO', 'kilo'), ('LB', 'lb'), ('UNIT', 'item'), ('UNDETERMINED', 'undetermined')], default='GRAM', max_length=13),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('DAIRY_AND_EGG_PRODUCTS', 'dairy and eggs'), ('SPICES_AND_HERBS', 'spices and herbs'), ('BABY_FOODS', 'baby foods'), ('FATS_AND_OILS', 'fats and oils'), ('POULTRY_PRODUCTS', 'poultry'), ('SOUPS_SAUCES_AND_GRAVIES', 'soups and sauces'), ('SAUSAGES_AND_LUNCHEON_MEATS', 'sausages and lunch meats'), ('BREAKFAST_CEREALS', 'breakfast cereals'), ('FRUITS_AND_FRUIT_JUICES', 'fruits and fruit juices'), ('PORK_PRODUCTS', 'pork'), ('VEGETABLES_AND_VEGETABLE_PRODUCTS', 'vegetables'), ('NUT_AND_SEED_PRODUCTS', 'nut and seed'), ('BEEF_PRODUCTS', 'beef'), ('BEVERAGES', 'beverages'), ('FINFISH_AND_SHELLFISH_PRODUCTS', 'fish and shellfish'), ('LEGUMES_AND_LEGUME_PRODUCTS', 'legumes'), ('LAMB_VEAL_AND_GAME_PRODUCTS', 'lamb, veal, and game'), ('BAKED_PRODUCTS', 'baked goods'), ('SWEETS', 'sweets'), ('CEREAL_GRAINS_AND_PASTA', 'cereals, grains, and pasta'), ('FAST_FOODS', 'fastfoods'), ('MEALS_ENTREES_AND_SIDE_DISHES', 'prepared meals'), ('SNACKS', 'snacks'), ('RESTAURANT_FOODS', 'restaurant foods'), ('ALCOHOLIC_BEVERAGES', 'alcoholic beverages'), ('OTHER', 'other')], default='OTHER', max_length=256),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='snack_or_meal',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('SNACK', 'snack'), ('MEAL', 'meal'), ('DESSERT', 'dessert')], default='MEAL', max_length=10),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
