# Generated by Django 3.2 on 2021-05-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_plan_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='in_planning',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_shopping',
        ),
    ]
