# Generated by Django 3.2 on 2021-05-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='private',
            new_name='public',
        ),
    ]
