# Generated by Django 3.2 on 2021-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_alter_ingquant_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='personalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingquant',
            name='unit',
            field=models.CharField(choices=[('GRAM', 'gram'), ('WTOZ', 'wt oz'), ('FLOZ', 'fl oz'), ('CUP', 'cup'), ('TSP', 'tsp'), ('TBSP', 'tbsp'), ('ML', 'ml'), ('CAN', 'can'), ('PINT', 'pint'), ('QUART', 'quart'), ('GALLON', 'gallon'), ('LITER', 'liter'), ('KILO', 'kilo'), ('LB', 'lb'), ('UNIT', 'item'), ('UNDETERMINED', '?')], default='GRAM', max_length=13),
        ),
    ]
