# Generated by Django 3.2 on 2021-05-23 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0018_auto_20210517_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingquant',
            name='unit',
            field=models.CharField(choices=[('GRAM', 'gram'), ('CUP', 'cup'), ('TBSP', 'tbsp'), ('TSP', 'tsp'), ('WTOZ', 'oz'), ('FLOZ', 'fl oz'), ('ML', 'ml'), ('CAN', 'can'), ('GALLON', 'gallon'), ('KILO', 'kilo'), ('LITER', 'liter'), ('LB', 'lb'), ('PINT', 'pint'), ('QUART', 'quart'), ('UNIT', ''), ('UNDETERMINED', '?')], default='GRAM', max_length=13),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('ALCOHOLIC_BEVERAGES', 'alcoholic beverages'), ('BABY_FOODS', 'baby foods'), ('BAKED_PRODUCTS', 'baked products'), ('BEEF_PRODUCTS', 'beef products'), ('BEVERAGES', 'beverages'), ('BREAKFAST_CEREALS', 'breakfast cereals'), ('CEREAL_GRAINS_AND_PASTA', 'cereal grains and pasta'), ('DAIRY_AND_EGG_PRODUCTS', 'dairy and egg products'), ('FAST_FOODS', 'fast foods'), ('FATS_AND_OILS', 'fats and oils'), ('FINFISH_AND_SHELLFISH_PRODUCTS', 'finfish and shellfish products'), ('FRUITS_AND_FRUIT_JUICES', 'fruits and fruit juices'), ('LAMB_VEAL_AND_GAME_PRODUCTS', 'lamb, veal, and game products'), ('LEGUMES_AND_LEGUME_PRODUCTS', 'legumes and legume products'), ('MEALS_ENTREES_AND_SIDE_DISHES', 'meals, entrees, and side dishes'), ('NUT_AND_SEED_PRODUCTS', 'nut and seed products'), ('PORK_PRODUCTS', 'pork products'), ('POULTRY_PRODUCTS', 'poultry products'), ('RESTAURANT_FOODS', 'restaurant foods'), ('SAUSAGES_AND_LUNCHEON_MEATS', 'sausages and lunch meats'), ('SNACKS', 'snacks'), ('SOUPS_SAUCES_AND_GRAVIES', 'soups, sauces, and gravies'), ('SPICES_AND_HERBS', 'spices and herbs'), ('SWEETS', 'sweets'), ('VEGETABLES_AND_VEGETABLE_PRODUCTS', 'vegetables and vegetable products'), ('AMERICAN_INDIAN_ALASKAN_NATIVE_FOODS', 'american indian/alaska native foods'), ('OTHER', 'other')], default='OTHER', max_length=256),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingquant',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist'),
        ),
        migrations.AddField(
            model_name='plan',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist'),
        ),
        migrations.AddField(
            model_name='shop',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist'),
        ),
    ]
