# Generated by Django 3.2 on 2021-05-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_mealplan_plannedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dessert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='snack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plannedmeal',
            name='meal',
            field=models.CharField(choices=[('DINNER', 'dinner'), ('DESSERT', 'dessert'), ('BREAKFAST', 'breakfast'), ('OTHER', 'other'), ('SNACK', 'snack'), ('LUNCH', 'lunch')], default='DINNER', max_length=10),
        ),
    ]
