# Generated by Django 3.2 on 2021-05-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_auto_20210525_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='people',
            field=models.IntegerField(default='2'),
        ),
        migrations.AlterField(
            model_name='plannedmeal',
            name='meal',
            field=models.CharField(choices=[('LUNCH', 'lunch'), ('DESSERT', 'dessert'), ('SNACK', 'snack'), ('DINNER', 'dinner'), ('BREAKFAST', 'breakfast'), ('OTHER', 'other')], default='DINNER', max_length=10),
        ),
    ]
