# Generated by Django 3.2 on 2021-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20210526_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedmeal',
            name='notes',
            field=models.CharField(blank=True, max_length=226, null=True),
        ),
        migrations.AlterField(
            model_name='plannedmeal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Ingredient'),
        ),
        migrations.AlterField(
            model_name='plannedmeal',
            name='meal',
            field=models.CharField(choices=[('BREAKFAST', 'breakfast'), ('LUNCH', 'lunch'), ('DINNER', 'dinner'), ('SNACK', 'snack'), ('DESSERT', 'dessert'), ('OTHER', 'other')], default='DINNER', max_length=10),
        ),
        migrations.AlterField(
            model_name='plannedmeal',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Recipe'),
        ),
    ]
