# Generated by Django 3.2 on 2021-07-13 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_auto_20210713_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedmeal',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingquant',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingquants', to='recipes.mealplan'),
        ),
    ]
