# Generated by Django 3.2 on 2021-07-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20210713_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='temp_servings',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe'),
        ),
    ]
