- hosts: app_srv
  vars:
    - ssp_name: sisepuede-stg
    - ssp_env: stg
    - ssp_user: sisepuede_stg
    - ssp_group: sisepuede_stg
    - ssp_root: /usr/lib/sisepuede/stg
    - local_root: ../web/deploy
    - subdomain: stg-aoakley
  roles:
    - web
